version: "3"

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    hostname: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive-metastore:
    build:
      context: ./hive-metastore
    image: hoangph3/hive-metastore:3.0.0
    container_name: hive-metastore
    hostname: hive-metastore
    ports:
    - 9083:9083
    depends_on:
      - mariadb
      - minio
      - minio-bucket

  cassandra:
    image: bitnami/cassandra:3.11.7
    container_name: cassandra
    hostname: cassandra
    ports:
      - 9042:9042
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: mysecretpassword
      CASSANDRA_PASSWORD_SEEDER: 'yes'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.0.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  minio:
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    container_name: minio
    hostname: minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data

  minio-bucket:
    image: minio/mc:RELEASE.2022-12-13T00-23-28Z
    container_name: minio-bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rb --force myminio/featurestore;
      /usr/bin/mc mb myminio/featurestore;
      /usr/bin/mc anonymous set public myminio/featurestore;
      exit 0;
      "

  pyspark-notebook:
    image: hoangph3/pyspark-notebook:3.2.0-fs
    container_name: pyspark-notebook
    hostname: pyspark-notebook
    ports:
      - 8888:8888
    volumes:
      - ./pyspark-notebook:/home/jovyan/work
